--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Arisify/Skywar
build-by-default: true
branches:
- master
projects:
  Skywar:
    path: ""
    libs:
      - src: Arisify/yamlcomments/yamlcomments
        version: ^1.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...
