name: Skywar
author: arie
main: arie\skywar\Skywar
website: https://github.com/Arisify/Skywar
version: 0.1alpha3
api: 4.0.0

versions:
  config: 0.1
  language: 0.1

permissions:
  skywar.cmd:
    description: Allows players to use Skywar commands
    default: op
  skywar.join:
    description: Allows players to join Arena
    default: true
  skywar.map_vote:
    description: Allows players to vote for the Maps
    default: true
  skywar.kit_vote:
    description: Allows players to vote for the Kits
    default: true
  skywar.chest_vote:
    description: Allows players to vote for the Chest Fills
    default: false
  skywar.vip:
    description: Allows players to have Vip, included chest voting
    default: false
  skywar.boost:
    description: Allows players to boost the waiting time
    default: false